laboratorio-2-jmalvarezbesa.git/config/routes.rb
Rails.application.routes.draw do
  resources :student_courses
  resources :courses
  resources :people
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

laboratorio-2-jmalvarezbesa.git/app/models/course.rb
class Course < ApplicationRecord
  belongs_to :Person
end

laboratorio-2-jmalvarezbesa.git/app/models/person.rb
class Person < ApplicationRecord
end

laboratorio-2-jmalvarezbesa.git/app/models/student_course.rb
class StudentCourse < ApplicationRecord
  belongs_to :Person
  belongs_to :Course
end

laboratorio-2-jmalvarezbesa.git/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @q = params[:q]
    if @q == ""
      @q = nil
    end
    if @q
      @courses = Course.where(:title => @q)
    else
      @courses = Course.all
    end
  end
  # GET /courses/1
  # GET /courses/1.json
  def show
    @student_courses = StudentCourse.where(:Course => Course.find(params[:id]))
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'El Curso fue creado exitosamente' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'El Curso fue actualizado exitosamente.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'El curso fue eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:title, :code, :Person_id)
    end
end

laboratorio-2-jmalvarezbesa.git/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:first_name, :last_name, :email)
    end
end

laboratorio-2-jmalvarezbesa.git/app/controllers/student_courses_controller.rb
class StudentCoursesController < ApplicationController
  before_action :set_student_course, only: [:show, :edit, :update, :destroy]

  # GET /student_courses
  # GET /student_courses.json
  def index
    @student_courses = StudentCourse.all
  end

  # GET /student_courses/1
  # GET /student_courses/1.json
  def show
  end

  # GET /student_courses/new
  def new
    @student_course = StudentCourse.new
  end

  # GET /student_courses/1/edit
  def edit
  end

  # POST /student_courses
  # POST /student_courses.json
  def create
    @student_course = StudentCourse.new(student_course_params)

    respond_to do |format|
      if @student_course.save
        format.html { redirect_to @student_course, notice: 'Student course was successfully created.' }
        format.json { render :show, status: :created, location: @student_course }
      else
        format.html { render :new }
        format.json { render json: @student_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /student_courses/1
  # PATCH/PUT /student_courses/1.json
  def update
    respond_to do |format|
      if @student_course.update(student_course_params)
        format.html { redirect_to @student_course, notice: 'Student course was successfully updated.' }
        format.json { render :show, status: :ok, location: @student_course }
      else
        format.html { render :edit }
        format.json { render json: @student_course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /student_courses/1
  # DELETE /student_courses/1.json
  def destroy
    @student_course.destroy
    respond_to do |format|
      format.html { redirect_to student_courses_url, notice: 'Student course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student_course
      @student_course = StudentCourse.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_course_params
      params.require(:student_course).permit(:Person_id, :Course_id)
    end
end

laboratorio-2-jmalvarezbesa.git/app/helpers/courses_helper.rb
module CoursesHelper
end

laboratorio-2-jmalvarezbesa.git/app/helpers/people_helper.rb
module PeopleHelper
end

laboratorio-2-jmalvarezbesa.git/app/helpers/student_courses_helper.rb
module StudentCoursesHelper
end

laboratorio-2-jmalvarezbesa.git/app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :code %>
    <%= f.number_field :code %>
  </div>

  <div class="field">
    <%= f.label :Person_id %>
    <%= f.text_field :Person_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

laboratorio-2-jmalvarezbesa.git/app/views/courses/edit.html.erb
<h1>Editar Curso</h1>

<%= render 'form', course: @course %>

<%= link_to 'Mostrar', @course %> |
<%= link_to 'Volver', courses_path %>

laboratorio-2-jmalvarezbesa.git/app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cursos</h1>

<table>
  <thead>
    <tr>
      <th>Nro</th>
      <th>Curso</th>
      <th>Código</th>
      <th>Profesor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @courses.each do |course| %>
      <tr>
        <td><%= course.id %></td>
        <td><%= course.title %></td>
        <td><%= course.code %></td>
        <td><%= course.Person.first_name %> <%= course.Person.last_name %></td>
        <td><%= link_to 'Detalle', course %></td>
        <td><%= link_to 'Editar', edit_course_path(course) %></td>
        <td><%= link_to 'Eliminar', course, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table><br />
<strong>Filtrar cursos por nombre:</strong><br />
<form>
  <input name="q" <%= @q %>>
  <button type="summit">Buscar</button>
</form>
<br>

<%= link_to 'Nuevo Curso', new_course_path %>

laboratorio-2-jmalvarezbesa.git/app/views/courses/new.html.erb
<h1>Nuevo Curso</h1>

<%= render 'form', course: @course %>

<%= link_to 'Volver', courses_path %>

laboratorio-2-jmalvarezbesa.git/app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Curso:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Código:</strong>
  <%= @course.code %>
</p>

<p>
  <strong>Profesor:</strong>
  <%= @course.Person.first_name %> <%= @course.Person.last_name %>
</p>

<p>
  <strong>Alumnos:</strong>
  <table>
    <thead>
      <tr>
        <th>Nro</th>
        <th>Alumno</th>
        <th>Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @student_courses.each do |student_course| %>
      <tr>
        <td><%= student_course.Person.id %></td>
        <td><%= student_course.Person.first_name %> <%= student_course.Person.last_name %></td>
        <td><%= student_course.Person.email %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</p>

<form>
  <p>
  <strong>Agregar Alumno:</strong><br />
  <select name="category[id]" <%= collection_select(:id, 1, Person.where.not(:id => @student_courses), :id, :email) %></select>
  <button type="summit">Agregar</button>
</p>
</form>

<%= link_to 'Editar', edit_course_path(@course) %> |
<%= link_to 'Volver', courses_path %>

laboratorio-2-jmalvarezbesa.git/app/views/people/_form.html.erb
<%= form_for(person) do |f| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

laboratorio-2-jmalvarezbesa.git/app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Mostrar', @person %> |
<%= link_to 'Volver', people_path %>

laboratorio-2-jmalvarezbesa.git/app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Personas</h1>

<table>
  <thead>
    <tr>
      <th>Nro</th>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.id %></td>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= person.email %></td>
        <td><%= link_to 'Mostrar', person %></td>
        <td><%= link_to 'Editar', edit_person_path(person) %></td>
        <td><%= link_to 'Eliminar', person, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

laboratorio-2-jmalvarezbesa.git/app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Volver', people_path %>

laboratorio-2-jmalvarezbesa.git/app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @person.first_name %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @person.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @person.email %>
</p>

<%= link_to 'Editar', edit_person_path(@person) %> |
<%= link_to 'Volver', people_path %>

laboratorio-2-jmalvarezbesa.git/app/views/student_courses/_form.html.erb
<%= form_for(student_course) do |f| %>
  <% if student_course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student_course.errors.count, "error") %> prohibited this student_course from being saved:</h2>

      <ul>
      <% student_course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Person_id %>
    <%= f.text_field :Person_id %>
  </div>

  <div class="field">
    <%= f.label :Course_id %>
    <%= f.text_field :Course_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

laboratorio-2-jmalvarezbesa.git/app/views/student_courses/edit.html.erb
<h1>Editing Student Course</h1>

<%= render 'form', student_course: @student_course %>

<%= link_to 'Mostrar', @student_course %> |
<%= link_to 'Volver', student_courses_path %>

laboratorio-2-jmalvarezbesa.git/app/views/student_courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estudiantes en Cursos</h1>

<table>
  <thead>
    <tr>
      <th>Nro</th>
      <th>Estudiante</th>
      <th>Curso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @student_courses.each do |student_course| %>
      <tr>
        <td><%= student_course.id %></td>
        <td><%= student_course.Person.first_name %> <%= student_course.Person.last_name %></td>
        <td><%= student_course.Course.title %></td>
        <td><%= link_to 'Mostrar', student_course %></td>
        <td><%= link_to 'Editar', edit_student_course_path(student_course) %></td>
        <td><%= link_to 'Eliminar', student_course, method: :delete, data: { confirm: '¿Estás seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Agregar estudiante a curso', new_student_course_path %>

laboratorio-2-jmalvarezbesa.git/app/views/student_courses/new.html.erb
<h1>Agregar alumno a curso</h1>

<%= render 'form', student_course: @student_course %>

<%= link_to 'Volver', student_courses_path %>

laboratorio-2-jmalvarezbesa.git/app/views/student_courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Alumno:</strong>
  <%= @student_course.Person.email%>
</p>

<p>
  <strong>Curso:</strong>
  <%= @student_course.Course.title %>
</p>

<%= link_to 'Editar', edit_student_course_path(@student_course) %> |
<%= link_to 'Volver', student_courses_path %>